version: '3'
services:
  hermes-server:
    container_name: hermes-server
    build: ./hermes-server
    image: hermes-server:latest
    ports:
      - 58080:8080
    networks:
      - hermes

networks:
  hermes:
    name: hermes
